import type { Match } from "./types";

const updated = "2026-07-14T08:00:00Z";

export const mockMatches: Match[] = [
  { id: "norway-england", slug: "norway-vs-england", tournamentId: "wc-2026", tournamentName: "World Cup 2026", stage: "Quarterfinal", kickoffUtc: "2026-07-12T20:00:00Z", status: "completed", homeTeam: { name: "Norway", code: "NOR", flag: "NO" }, awayTeam: { name: "England", code: "ENG", flag: "GB-ENG" }, venue: { name: "MetLife Stadium", city: "East Rutherford" }, score: { home: 1, away: 2 }, providerUpdatedAt: updated },
  { id: "france-mexico", slug: "france-vs-mexico", tournamentId: "wc-2026", tournamentName: "World Cup 2026", stage: "Quarterfinal", kickoffUtc: "2026-07-13T20:00:00Z", status: "completed", homeTeam: { name: "France", code: "FRA", flag: "FR" }, awayTeam: { name: "Mexico", code: "MEX", flag: "MX" }, venue: { name: "Hard Rock Stadium", city: "Miami Gardens" }, score: { home: 2, away: 0 }, providerUpdatedAt: updated },
  { id: "spain-argentina", slug: "spain-vs-argentina", tournamentId: "wc-2026", tournamentName: "World Cup 2026", stage: "Quarterfinal", kickoffUtc: "2026-07-14T00:00:00Z", status: "completed", homeTeam: { name: "Spain", code: "ESP", flag: "ES" }, awayTeam: { name: "Argentina", code: "ARG", flag: "AR" }, venue: { name: "SoFi Stadium", city: "Inglewood" }, score: { home: 1, away: 2 }, providerUpdatedAt: updated },
  { id: "france-spain", slug: "france-vs-spain", tournamentId: "wc-2026", tournamentName: "World Cup 2026", stage: "Semifinal", kickoffUtc: "2026-07-14T19:00:00Z", status: "scheduled", homeTeam: { name: "France", code: "FRA", flag: "FR" }, awayTeam: { name: "Spain", code: "ESP", flag: "ES" }, venue: { name: "Mercedes-Benz Stadium", city: "Atlanta" }, providerUpdatedAt: updated },
  { id: "semi-final-two", slug: "semi-final-two", tournamentId: "wc-2026", tournamentName: "World Cup 2026", stage: "Semifinal", kickoffUtc: "2026-07-15T19:00:00Z", status: "scheduled", homeTeam: { name: "Winner of QF 1", code: "QF1", flag: "" }, awayTeam: { name: "Winner of QF 2", code: "QF2", flag: "" }, venue: { name: "AT&T Stadium", city: "Arlington" }, providerUpdatedAt: updated },
  { id: "world-cup-final", slug: "world-cup-final", tournamentId: "wc-2026", tournamentName: "World Cup 2026", stage: "Final", kickoffUtc: "2026-07-19T19:00:00Z", status: "scheduled", homeTeam: { name: "Winner of Semifinal 1", code: "SF1", flag: "" }, awayTeam: { name: "Winner of Semifinal 2", code: "SF2", flag: "" }, venue: { name: "MetLife Stadium", city: "East Rutherford" }, providerUpdatedAt: updated },
];
